source 'https://github.com/CocoaPods/Specs.git'

platform:ios, '9.0'
use_frameworks!

target 'WZRoute_Example' do
  pod 'WZRoute', :path => '../'
 
  target 'WZRoute_Tests' do
    inherit! :search_paths

    
  end
end
