
platform:ios, '11.0'
use_frameworks!

target 'WZRoute_Example' do
  pod 'WZRoute', :path => '../'
 
  target 'WZRoute_Tests' do
    inherit! :search_paths

    
  end
  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    end
    installer.pods_project.targets.each do |target|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
      end
    end
  end
end
